name: Check Bootnodes ENRs

on:
  pull_request:
    branches:
      - main

jobs:
  check_enrs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install python3

      - name: Check bootnodes ENRs have no padding
        run: |
          for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
            ENR_STRINGS=$(grep -Eo '"enr:([a-zA-Z0-9+/]+={0,2})"' "$FILE" | sed 's/"enr://g' | sed 's/"//g')
            for ENR_STRING in $ENR_STRINGS; do
              BASE64_STRING=${ENR_STRING#*enr:}
              if [[ "$BASE64_STRING" =~ = ]]; then
                echo "Base64 string in $FILE after 'enr:' contains padding."
                exit 1
              fi
            done
          done

      - name: Decode Base64
        run: |
          for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
            ENR_STRINGS=$(grep -Eo '"enr:([a-zA-Z0-9+/]+={0,2})"' "$FILE" | sed 's/"enr://g' | sed 's/"//g')
            for ENR_STRING in $ENR_STRINGS; do
              BASE64_STRING=${ENR_STRING#*enr:}
              DECODED_STRING=$(echo "$BASE64_STRING" | base64 -d 2>/dev/null)
              if [ $? -eq 0 ]; then
                echo "Decoded base64 string in $FILE after 'enr:': $DECODED_STRING"
              else
                echo "Base64 string after 'enr:' could not be decoded: $BASE64_STRING"
              fi
            done
          done
