name: Check Bootnodes ENRs

on:
  pull_request:
    branches:
      - main

jobs:
  check_padding:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install python3

      - name: Check bootnodes ENRs have no padding
        run: |
          for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
            BASE64_STRINGS=$(grep -Eo '^[[:space:]]*[- ]*["]?([a-zA-Z0-9+/]+={0,2})[[:space:]]*[- ]*["]?' "$FILE" | sed 's/"//g')
            for BASE64_STRING in $BASE64_STRINGS; do
              if [[ "$BASE64_STRING" == *"="* ]]; then
                echo "ENR string in $FILE contains padding."
                exit 1
              fi
            done
          done

      - name: Decode Base64
        run: |
          for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
            BASE64_STRINGS=$(grep -Eo '^[[:space:]]*[- ]*["]?([a-zA-Z0-9+/]+={0,2})[[:space:]]*[- ]*["]?' "$FILE" | sed 's/"//g')
            for BASE64_STRING in $BASE64_STRINGS; do
              DECODED_STRING=$(echo "$BASE64_STRING" | base64 -d)
              echo "Succesfully decoded ENR in $FILE: $DECODED_STRING"
            done
          done