name: Check Bootnodes ENRs

on:
  pull_request:
    branches:
      - main

jobs:
  check_padding:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check bootnodes ENRs have no padding
        run: |
          for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
            BASE64_STRING=$(grep -Eo '^[[:space:]]*[- ]*["]?([a-zA-Z0-9+/]+={0,2})[[:space:]]*[- ]*["]?' "$FILE" | sed 's/"//g')
            if [[ $BASE64_STRING == *"="* ]]; then
              echo "Base64 string in $FILE contains padding."
              exit 1
            fi
          done
