name: Check Bootnodes ENRs

on:
  pull_request:
    branches:
      - main

jobs:
  check_enrs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install python3

      - name: Check bootnodes ENRs have no padding
        run: |
          for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
            echo "Checking paddings in file: $FILE"
            while read -r LINE; do
              if [[ "$LINE" =~ enr: ]]; then
                BASE64_STRING=${LINE#enr:}
                if [[ "$BASE64_STRING" =~ = ]]; then
                  echo "ENR in $FILE contains padding: $LINE"
                  exit 1
                fi
              fi
            done < "$FILE"
          done

      - name: Decode Base64
        run: |
          for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
            echo "Test decoding in file: $FILE"
            while read -r LINE; do
              if [[ "$LINE" =~ enr: ]]; then
                BASE64_STRING=${LINE#enr:}
                DECODED_STRING=$(echo "$BASE64_STRING" | base64 -d 2>/dev/null)
                if [ $? -eq 0 ]; then
                  echo "Succesfully decoded base64: $LINE"
                else
                  echo "ENR could not be decoded: $LINE"
                fi
              fi
            done < "$FILE"
          done

