name: Update Config

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 */4 * * *'  # Runs every 4 hours

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check mainnet config is synced
      run: ./scripts/sync_config.sh
    - name: Check chiado config is synced
      run: ./scripts/sync_chiado_config.sh
